ItemNames:
	db "BOLA MESTRE@"
	db "ULTRA BOLA@"
	db "GRANDE BOLA@"
	db "POKé BOLA@"
	db "MAPA@"
	db "BICICLETA@"
	db "?????@"
	db "BOLA SAFARI@"
	db "POKéDEX@"
	db "PEDRA LUA@"
	db "ANTIDOTO@"
	db "ESFRIA@"
	db "ESQUENTA@"
	db "ACORDAR@"
	db "DESPARALISAR@"
	db "CURA TUDO@"
	db "POCAO MAXIMA@"
	db "HIPER POCAO@"
	db "SUPER POCAO@"
	db "POCAO@"
	db "EMBLEMA PEDRA@"
	db "EMBLEMA CASCATA@"
	db "EMBLEMA TROVAO@"
	db "EMBLEMA ARCO-IRIS@"
	db "EMBLEMA ALMA@"
	db "EMBLEMA PANTANO@"
	db "EMBLEMA VULCAO@"
	db "EMBLEMA TERRA@"
	db "CORDA@"
	db "REPELENTE@"
	db "AMBAR VELHO@"
	db "PEDRA FOGO@"
	db "PEDRA TROVAO@"
	db "PEDRA AGUA@"
	db "HP UP@"
	db "PROTEINA@"
	db "FERRO@"
	db "CARBONO@"
	db "CALCIO@"
	db "DOCE RARO@"
	db "FOSSIL CUPULA@"
	db "FOSSIL CONCHA@"
	db "CHAVE SECRETA@"
	db "?????@"
	db "BIKE BILHETE@"
	db "PRECISAO X@"
	db "PEDRA FOLHA@"
	db "CARTAO@"
	db "PEPITA@"
	db "PP UP@"
	db "POKé BONECO@"
	db "SUPER CURA@"
	db "REVIVE@"
	db "REVIVE TUDO@"
	db "GUARDA SPEC.@"
	db "SUPER REPELENTE@"
	db "REPELENTE MAX@"
	db "GOLPE CERTEIRO@"
	db "MOEDA@"
	db "FRESCA AGUA@"
	db "SODA POP@"
	db "LIMONADA@"
	db "S.S.TICKET@"
	db "DENTADURA@"
	db "ATAQUE X@"
	db "DEFESA X@"
	db "VELOCIDADE X@"
	db "ESPECIAL X@"
	db "BOLSA DE MOEDA@"
	db "PACOTE OAK@"
	db "DETECTOR@"
	db "OCULOS SILPH@"
	db "POKé FLAUTA@"
	db "CARTAO DO ELEVADOR@"
	db "CAPACETE@"
	db "VARA VELHA@"
	db "VARA BOA@"
	db "SUPER VARA@"
	db "PP UP@"
	db "ETER@"
	db "ETER MAXIMO@"
	db "ELIXIR@"
	db "ELIXIR MAXIMO@"
	db "B2F@"
	db "B1F@"
	db "1F@"
	db "2F@"
	db "3F@"
	db "4F@"
	db "5F@"
	db "6F@"
	db "7F@"
	db "8F@"
	db "9F@"
	db "10F@"
	db "11F@"
	db "B4F@"
